# Verification Rules Configuration for LedgerFlow
# This file contains all validation rules, constants, and business logic

# Invoice number patterns by country and type
invoice_patterns:
  India:
    gst: "^GST/\\d{4}-\\d{2}/\\d{6}$|^GST-\\d{4}-\\d{6}$|^GST-\\d{8}-\\d{4}$"
    cash: "^CASH/\\d{2}/\\d{6}$|^CASH-\\d{4}-\\d{6}$|^CASH-\\d{8}-\\d{4}$"
    plain: "^INV-\\d{4}-\\d{6}$|^INV-\\d{8}-\\d{4}$"
  Bahrain:
    vat: "^VAT/BH/\\d{6}/\\d{4}$|^VAT-\\d{4}-\\d{6}$|^VAT-\\d{8}-\\d{4}$"
    cash: "^CASH/\\d{2}/\\d{6}$|^CASH-\\d{4}-\\d{6}$|^CASH-\\d{8}-\\d{4}$"

# Template-specific field requirements
template_requirements:
  gst_einvoice:
    required_fields:
      - business_gst_number
      - place_of_supply
      - cgst_amount
      - sgst_amount
      - igst_amount
    currency: INR
    tax_structure: gst
    compliance_level: government_grade
  bahrain_vat:
    required_fields:
      - business_vat_number
      - vat_amount
      - total_ex_vat
    currency: BHD
    tax_structure: vat
    compliance_level: government_grade
  plain_cash:
    required_fields:
      - total_amount_in_words
    currency: INR
    tax_structure: none
    compliance_level: basic

# Business rules and constraints
business_rules:
  max_invoice_amount: 10000000  # 1 crore
  max_items_per_invoice: 50
  min_invoice_amount: 0.01
  max_discount_percentage: 50
  future_date_tolerance_days: 0
  past_date_tolerance_days: 365

# Tax calculation tolerances
tax_tolerances:
  tax_calculation: 2.0
  cgst_sgst: 1.0
  igst: 1.0
  vat: 1.0
  invoice_tax_total: 2.0

# Compliance scoring weights
compliance_scoring:
  critical_error_penalty: 20
  warning_penalty: 5
  base_score: 100

# Risk level thresholds
risk_levels:
  critical_threshold: 0  # Any critical errors
  high_threshold: 70
  medium_threshold: 85
  low_threshold: 100

# Business style expectations
business_style_expectations:
  retail_shop:
    min_items: 1
    max_items: 10
    min_amount: 10
    max_amount: 10000
  distributor:
    min_items: 5
    max_items: 50
    min_amount: 100
    max_amount: 100000
  exporter:
    min_items: 10
    max_items: 100
    min_amount: 1000
    max_amount: 1000000
  pharmacy:
    min_items: 1
    max_items: 20
    min_amount: 20
    max_amount: 5000
  it_service:
    min_items: 1
    max_items: 10
    min_amount: 1000
    max_amount: 500000

# GST number validation patterns
gst_patterns:
  business_gst: "^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$"
  customer_gst: "^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$"

# HSN code validation
hsn_patterns:
  basic: "^\\d{4,8}$"
  high_value_threshold: 5000

# Sample invoice numbers for error messages
sample_invoice_numbers:
  gst: GST-2025-000001
  vat: VAT-2025-000001
  cash: CASH-2025-000001
  plain: INV-2025-000001

# Required fields for basic validation
required_fields:
  - invoice_number
  - invoice_date
  - customer_name
  - items
  - total_amount
  - invoice_type

# Required item fields
required_item_fields:
  - name
  - quantity
  - unit_price

# Validation severity levels
severity_levels:
  - critical
  - warning
  - info

# Risk levels
risk_levels_list:
  - low
  - medium
  - high
  - critical 